kind: pipeline
name: merchant_api

clone:
  disable: true

steps:
  - name: docker-merchant
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/copo_schedule
        - git checkout -- .
        #- git checkout -- .
        - git pull origin dev
        - go mod tidy
        - docker-compose down
        - docker rmi -f $(docker images --filter="reference=schedule_service" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o schedule_service main.go
        - docker build -t schedule_service .
        - docker-compose  up -d
    when:
      branch:
        - dev
      event:
        - push
        
trigger:
  branch:
    - dev
