---
kind: pipeline
type: docker
name: schedule-deploy

clone:
  disable: true

steps:
- name: slb-before-api01
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api01-before.sh
  when:
    ref:
      - refs/tags/api01-sch*
      - refs/tags/api01-test*

- name: slb-before-api02
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api02-before.sh
  when:
    ref:
      - refs/tags/api02-sch*
      - refs/tags/api02-test*

- name: docker-merchant-api01
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api01-host
    username: 
      from_secret: api01-user
    password:
      from_secret: api01-pwd
    port:
      from_secret: api01-port
    command_timeout: 180m
    script:
      - cd /root/copo_schedule
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi schedule_service:latest
      - docker image prune -f
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o schedule_service main.go
      - DOCKER_BUILDKIT=1 docker build -t schedule_service .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api01-sch*
      - refs/tags/api01-test*
    status:
      - success

- name: docker-merchant-api02
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api02-host
    username: 
      from_secret: api02-user
    password:
      from_secret: api02-pwd
    port:
      from_secret: api02-port
    command_timeout: 180m
    script:
      - cd /root/copo_schedule
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi schedule_service:latest
      - docker image prune -f
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o schedule_service main.go
      - DOCKER_BUILDKIT=1 docker build -t schedule_service .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api02-sch*
      - refs/tags/api02-test*
    status:
      - success

- name: slb-after
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api-after.sh
  when:
    ref:
      - refs/tags/api01-sch*
      - refs/tags/api02-sch*
      - refs/tags/api-bal*
