kind: pipeline
name: copo_schedule

clone:
  disable: true

steps:
  - name: docker
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/schedule_service
        - git checkout -- .
        - git checkout dev
        - git pull origin dev
        - git checkout -- .
        - go mod tidy
        - docker-compose down
        - docker rmi -f $(docker images --filter="reference=schedule_service" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin boadmin.go
        - docker build -t schedule_service -f boadmin/Dockerfile .
        - docker-compose up -d
    when:
      branch:
        - dev
      event:
        - push